required = ["github.com/json-iterator/go"]

[[constraint]]
  name = "github.com/linode/linodego"
  version = "0.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "=1.1.5"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=1.11.3"

[prune]
  go-tests = true
  unused-packages = true
