apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ccm-linode
  labels:
    app: ccm-linode
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ccm-linode
    spec:
      containers:
        - image: linode/linode-cloud-controller-manager:canary
          name: ccm-linode
          ports:
            - containerPort: 9844
              name: web
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ccm-linode
  labels:
    app: ccm-linode
spec:
  ports:
  - port: 9844
    protocol: TCP
    targetPort: web
  selector:
    app: ccm-linode
